version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache-container
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: jwt_api
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  composer:
    image: composer:2
    container_name: composer-container
    volumes:
      - .:/app
    working_dir: /app
    command: ["composer", "install"]

volumes:
  db_data:
